### ISSUE TITLE
DNS Requests, appends .local, double pings

### ISSUE THREAD

**Issue by LewisSpring** [AlexGustafsson/homebridge-wol#143] opened 2021-02-17 09:42 UTC
### Backstory
I checked my PiHole to see that there were DNS requests for these domains.
- local
- hostname1.local
- honstame1.local.local
- (repeat for hostname2)

### Issue
Pings made by the plugin are being sent to the DNS server. I don't think there should be DNS requests made for these pings. I've tried pinging locally from my PC and no DNS requests are made.
The addition of .local to the hostname I already added is also an issue.

### Environment
* os & os version:  Raspbian GNU/Linux Buster (10)
* node version:  14.15.5
* homebridge version:  1.1.7
* homebridge-wol version:  Latest

### Configuration
My configuration looks like this:
```
`
        {
            "name": "A WOL",
            "ip": "A.local",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "<mac-address>",
            "broadcastAddress": "192.168.0.255",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownCommand": "curl -X POST https://",
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": false,
            "debugLog": true,
            "returnEarly": false,
            "accessory": "NetworkDevice"
        },
        {
            "name": "BWOL",
            "ip": "B.local",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "<mac-address>",
            "broadcastAddress": "192.168.0.255",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": false,
            "debugLog": true,
            "returnEarly": false,
            "accessory": "NetworkDevice"
        }`
IMPORTANT!
Remove any mac addresses from the configuration by
exchanging them with <mac-address>
```

### Log
When I follow these steps:
1. Make sure `logLevel` is set to `Debug` on all `NetworkDevice` accessories
2. Run `homebridge`
3. Let it run for a couple of minutes
4. Try to turn a device on or off using the plugin
5. Wait one minute
6. Repeat step 4

I get the following log:
```
[17/02/2021, 09:38:33] [A WOL] Attempting to ping "A WOL" (A.local)
[17/02/2021, 09:38:33] [B WOL] Attempting to ping "B WOL" (B.local)
[17/02/2021, 09:38:33] [B WOL] Result of pinging "B WOL" (B.local): online
[17/02/2021, 09:38:33] [A WOL] Result of pinging "A WOL" (A.local): online
[17/02/2021, 09:38:35] [A WOL] Attempting to ping "A WOL" (A.local)
[17/02/2021, 09:38:35] [B WOL] Attempting to ping "B WOL" (B.local)
[17/02/2021, 09:38:35] [A WOL] Result of pinging "A WOL" (A.local): online
[17/02/2021, 09:38:35] [B WOL] Result of pinging "B WOL" (B.local): online
[17/02/2021, 09:38:37] [A WOL] Attempting to ping "A WOL" (A.local)
[17/02/2021, 09:38:37] [B WOL] Attempting to ping "B WOL" (B.local)
[17/02/2021, 09:38:37] [A WOL] Result of pinging "A WOL" (A.local): online
[17/02/2021, 09:38:37] [B WOL] Result of pinging "B WOL" (B.local): online
[17/02/2021, 09:38:39] [A WOL] Attempting to ping "A WOL" (A.local)
[17/02/2021, 09:38:39] [B WOL] Attempting to ping "B WOL" (B.local)
[17/02/2021, 09:38:39] [B WOL] Result of pinging "B WOL" (B.local): online
[17/02/2021, 09:38:39] [B WOL] Got 5 positives out of 5
[17/02/2021, 09:38:39] [B WOL] Got state change from pinger for "B WOL" (B.local): online
[17/02/2021, 09:38:39] [A WOL] Result of pinging "A WOL" (A.local): online
[17/02/2021, 09:38:39] [A WOL] Got 5 positives out of 5
[17/02/2021, 09:38:39] [A WOL] Got state change from pinger for "A WOL" (A.local): online
[17/02/2021, 09:38:41] [A WOL] Attempting to ping "A WOL" (A.local)
[17/02/2021, 09:38:41] [B WOL] Attempting to ping "B WOL" (B.local)
[17/02/2021, 09:38:41] [A WOL] Result of pinging "A WOL" (A.local): online
[17/02/2021, 09:38:41] [B WOL] Result of pinging "B WOL" (B.local): online
[17/02/2021, 09:38:43] [A WOL] Attempting to ping "A WOL" (A.local)
```

### Notes
Please write about things that you did not see fit the above headers.

Thanks!

**Comment by AlexGustafsson** [comment] 2021-02-17 10:57
The DNS queries are to be expected. There's not much I can do about that. The queries will have to happen at one point or another, the only question is whether or not they will be cached. What's likely happening is that the server running homebridge isn't caching queries. Whether this is up to NodeJS or the local resolver running on the client is anyone's guess.

I'm not quite sure I understand what you're saying the issue with appending `.local` is. It's the job of the DNS server to assume that `my-macbook` etc. is under `.local` or `.localdomain` and then resolve that to a local IP address. I haven't come across a DNS server that forces you to append `.local` when querying. Does it not work for you when you leave the domain out of the hostname in the config? If it's PiHole showing `.local` everywhere, then that's not an issue since `my-macbook` and `my-macbook.local` are equivalent and PiHole may chose to represent it either way.

As for the double pings, that's something that sure sounds like a bug. Are you able to try out #124 and see if the issue is solved?

**Comment by AlexGustafsson** [comment] 2021-02-17 11:01
Oh, wait, I think there might be a misunderstanding about the double pings. 

The following line is logged right before the ping occurs.

```
[17/02/2021, 09:38:33] [A WOL] Attempting to ping "A WOL" (A.local)
```

The following line is logged right after a ping response is received.
```
[17/02/2021, 09:38:33] [A WOL] Result of pinging "A WOL" (A.local): online
```

That is, both lines refer to the same ping.

Furthermore, if you check the timestamps you can see that a pair of these lines is only logged every two seconds which is in line with your configured `pingInterval`.

**Comment by LewisSpring** [comment] 2021-02-17 22:00
Hi there! Thank you for clarifying the double pings. I must have left that in the title - I had worked that out!

If I do not append .local, the ping status check does not work. The only client adding .local.local is the homebridge.
I'm not sure why this is happening, it's definitely an issue with the homebridge/plugin, it does not happen elsewhere.

**Comment by LewisSpring** [comment] 2021-02-17 22:06
Looks like either Homebridge or the Pi are causing issues with DNS:
I'm seeing DNS requests to "local", and getting ".local.local" for my Drayton Wiser heating too.

**Comment by AlexGustafsson** [comment] 2021-02-17 22:12
This plugin uses [https://github.com/danielzzz/node-ping](https://github.com/danielzzz/node-ping) internally to perform pings when a hostname is set. The configured hostname will be used as is without alteration. If you think there's an issue with how DNS is handled, it would be great if you could open an issue about it there.

Basically, all this plugin does as far as pings are concerned is this:

https://github.com/AlexGustafsson/homebridge-wol/blob/e5142c987a41b0947c1fa98d247262eac65f8abf/src/pinger.ts#L54

A quick search though the repository yields no luck when it comes to why `.local` would be appended. The safest bet is likely PiHole itself, as you've found the issue elsewhere as well.

**Comment by LewisSpring** [comment] 2021-02-17 22:14
I've asked on the Homebridge Discord.
Since this does not happen elsewhere on my network, and the homebridge Pi is the only one affected.

Thank you for your help: I'll have to see if Drayton-Wiser does this too, and if so i'll add an issue.

**Comment by AlexGustafsson** [comment] 2021-03-14 20:46
I'm going ahead and closing this. The plugin doesn't handle the hostname you enter in any special way. It uses the value verbatim when calling the node-ping library mentioned previously.

**Closed by AlexGustafsson** 2021-03-14 20:46 UTC
Labels: bug
