### ISSUE TITLE
startCommand error

### ISSUE THREAD

**Issue by EstrellaXD** [AlexGustafsson/homebridge-wol#186] opened 2022-01-14 03:16 UTC
I want to start my PS5 using [ps5-wake](https://github.com/iharosi/ps5-wake), It works well on my pi, but when I set it to the startCommadn in WoL plugin it shows the error like that
`TypeError: Cannot read properties of null (reading 'split')
    at NetworkDevice.wake (/usr/lib/node_modules/homebridge-wol/lib/network-device.js:185:51)
    at NetworkDevice.setOnline (/usr/lib/node_modules/homebridge-wol/lib/network-device.js:136:14)
    at On.emit (node:events:390:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1668:16
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1666:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)`
I don't know how to fix it.
Thank you

**Comment by AlexGustafsson** [comment] 2022-01-17 16:37
What version of homebridge-wol are you using?

**Comment by EstrellaXD** [comment] 2022-01-17 16:38
The latest version, homebridge-wol v4.3.0.
Thank you

**Comment by AlexGustafsson** [comment] 2022-01-17 17:04
Could you try running v5.0.0? See #124.

**Comment by EstrellaXD** [comment] 2022-01-18 02:07
Thank you for reply! I have tried 5.0.0-beta2, the startCommand works well, but there is something wrong with the shutdown command.
`[1/18/2022, 2:05:06 AM] [PlayStation 5] [NetworkDevice] Attempting to shut down the device using "playactor"
[1/18/2022, 2:05:07 AM] [PlayStation 5] [NetworkDevice] An error occured while trying to shut down the device`

**Comment by EstrellaXD** [comment] 2022-01-18 02:11
I used the debug option and here's the log
` [PlayStation 5] [NetworkDevice] An error occured while trying to shut down the device
[1/18/2022, 2:11:12 AM] [PlayStation 5] [NetworkDevice] Error: Command failed: playactor standby --host-name PS5-202
Error: Error[2] UNKNOWN_ERROR
    at Object.<anonymous> (/usr/lib/node_modules/playactor/dist/socket/helpers.js:76:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/playactor/dist/socket/helpers.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by AlexGustafsson** [comment] 2022-01-21 15:17
What happens if you run `playactor standby --host-name PS5-202` in your terminal? It seems as if the plugin is working fine, but the command itself returns an error. The command must return exit code 0 (indicating no error). If you try to run the command, but no error is shown, try to run `echo "$?"` directly after having run the specified shutdown command. It will print the exit code of whatever command was run before it. If it prints anything other than `0`, it indicates an error.

**Comment by hillaliy** [comment] 2022-01-27 18:53
Hi I have the same problem "An error occured while trying to shut down the device".
I try to run echo "$?" after the shutdown command and I get 0.
If I run the command from the UI terminal the PC turn off but from the Accessory don't work.

**Comment by AlexGustafsson** [comment] 2022-01-29 07:14
@hillaliy Did you try the new beta as well? I'm just trying to make sure the issue isn't already fixed.

**Comment by hillaliy** [comment] 2022-01-29 07:18
yes I'm on 5.0.0 beta 2

**Comment by AlexGustafsson** [comment] 2022-01-29 09:18
@hillaliy Could you try specifying a value for `shutdownCommandTimeout`? Something like `999999`. It could be that a timeout of 0 isn't properly treated as meaning no timeout at all. This would lead the command to immediately time out when run, leading to the issue you've described.

**Comment by hillaliy** [comment] 2022-01-29 09:24
I add shutdownCommandTimeout: 999999
same error

**Comment by AlexGustafsson** [comment] 2022-01-29 09:32
Could you specify `logLevel` `Debug` and post the error that is thrown? It should be verbose telling you what the issue is.

**Comment by AlexGustafsson** [comment] 2022-01-29 09:40
This could be an instance of #156.

**Comment by AlexGustafsson** [comment] 2022-01-29 09:52
> This could be an instance of #156.

Turns out it likely isn't.

**Comment by hillaliy** [comment] 2022-01-29 10:38
I try Debug mode same error "'An error occured while trying to shut down the device'"
Didn't get verbose.
If I activate the command from terminal through homebridge UI the command works.
So all of my PC configuration is OK.

**Comment by AlexGustafsson** [comment] 2022-01-29 11:01
Please double check your plugin configuration. Setting `logLevel: "Debug"` should work. It should produce logs as those from ExtrellaXD's comments.

> I used the debug option and here's the log
> ` [PlayStation 5] [NetworkDevice] An error occured while trying to shut down the device [1/18/2022, 2:11:12 AM] [PlayStation 5] [NetworkDevice] Error: Command failed: playactor standby --host-name PS5-202 Error: Error[2] UNKNOWN_ERROR at Object.<anonymous> (/usr/lib/node_modules/playactor/dist/socket/helpers.js:76:19) at Generator.next (<anonymous>) at fulfilled (/usr/lib/node_modules/playactor/dist/socket/helpers.js:5:58) at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by hillaliy** [comment] 2022-01-29 19:19
[1/29/2022, 9:18:00 PM] [Basement PC] [NetworkDevice] Got user-triggered state change: 0
[1/29/2022, 9:18:00 PM] [Basement PC] [NetworkDevice] Shutdown cycle started
[1/29/2022, 9:18:00 PM] [Basement PC] [NetworkDevice] Device went from status "Online" to "ShuttingDown"
[1/29/2022, 9:18:00 PM] [Basement PC] [Pinger] Stopping pinger
[1/29/2022, 9:18:00 PM] [Basement PC] [NetworkDevice] Attempting to shut down the device using "ssh"
[1/29/2022, 9:18:00 PM] [Basement PC] [NetworkDevice] An error occured while trying to shut down the device
[1/29/2022, 9:18:00 PM] [Basement PC] [NetworkDevice] Error: Command failed: ssh -o StrictHostKeyChecking=no -i /homebridge/id_rsa Hillali@192.168.0.187 shutdown /s
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/homebridge/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/homebridge/id_rsa": bad permissions
Permission denied, please try again.
Permission denied, please try again.
Hillali@192.168.0.187: Permission denied (publickey,password,keyboard-interactive).

**Comment by AlexGustafsson** [comment] 2022-02-01 16:47
Great, thanks! This tells us that there's no issue with the plugin, rather your command. As you can see the permissions for the SSH key is wrong.

```
Permissions 0644 for '/homebridge/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
```

**Comment by AlexGustafsson** [comment] 2022-02-01 16:48
As both of you seem to have issues with the command and not the plugin, I'm going ahead and closing this issue. Feel free to open a discussion about it if the issue persists.

I'll add extra logging to make it more clear when it could be a plugin issue and when it's not, like in this case.

**Closed by AlexGustafsson** 2022-02-01 16:48 UTC

**Comment by AlexGustafsson** [comment] 2022-02-01 17:09
A third beta has been released to make the logs more helpful, please try it out!

https://github.com/AlexGustafsson/homebridge-wol/releases/tag/v5.0.0-beta.3

See also: https://github.com/AlexGustafsson/homebridge-wol/wiki/Frequently-Asked-Questions
