### ISSUE TITLE
Documentation around pingCommand

### ISSUE THREAD

**Issue by perry-mitchell** [AlexGustafsson/homebridge-wol#58] opened 2019-02-24 11:36 UTC
Hi!

Great plugin.. I'm already using it for both my Mac Mini and Windows PC. I'm just trying to get the WOL functionality working with the mac - it sleeps fine, but detecting that it is asleep is tricky. I saw that you added `pingCommand` for this, but I haven't yet found any example of how this is supposed to work.

Perhaps an example of how this should work when connecting to a Mac would be useful for others as well?

**Comment by perry-mitchell** [comment] 2019-02-24 11:38
Also, I'm not entirely sure but it looks like you haven't pushed a new version with `pingCommand` support?

**Comment by AlexGustafsson** [comment] 2019-02-24 12:17
Hi!

Well, the examples for this project is pretty sparse, but I do keep the configuration in the README up to date. For the `pingCommand` the following section is relevant:

> `pingCommand` Command to run in order to know if a host is up or not. If the command exits successfully (non-zero exit code) the host is considered up. If an error is thrown or the command exits with a non-zero exit code, the host is considered down.

As for examples, it's important to note that the ping command is any command that can be run in a shell. Therefore there are endless ways to use it. Unfortunately there's no go-to way for me to solve detection of a Mac being awake / asleep, so using the ping command to for example SSH into the machine and then doing the checks there is necessary. If I find a good way of doing it, I'll try to mention it or implement it into the plugin, but for now users will have to do some experimenting.

A good (untested) place to start is probably something like:
```shell
ssh user@mac.local "[[ "$(ioreg -n IODisplayWrangler | grep IOPowerManagement | sed 's/.*DevicePowerState"=\([0-9]\).*/\1/')" != "4" ]] && exit 1"
```
The command SSHs into the machine and sees if the value `IOPowerManagement` in the registry `IODisplayWrangler` is not equal to 4 (considered on). If it is not on, it exits with an error as specified by the `pingCommand` implementation. 

Inspired by: https://apple.stackexchange.com/a/103346

The ping command feature is implemented but untested, therefore I have decided not to push the feature to NPM. There's still some work to be done. The idea is to take care of everything mentioned in the [3.3 milestone](https://github.com/AlexGustafsson/homebridge-wol/milestone/1).

You can try the master version by following the steps outlined in the `Development` section of the README.

If you got further questions, don't hesitate to reach out!

**Comment by perry-mitchell** [comment] 2019-02-27 12:33
@AlexGustafsson Thanks for the details! I appreciate the effort. I'm looking forward to the 3.3 release :)

**Comment by amaisano** [comment] 2019-06-22 01:23
Here's my command in bash script form. It takes two args so it can be used for various Macs:

`pingHostDisplay <user> <IP>`

```
# anything less than 4 means display is off

STATE=$(ssh $1@$2 -i ~/.ssh/homebridge pmset -g powerstate IODisplayWrangler | tail -1 | cut -c29)

if [ "$STATE" != 4 ]; then
  # host is "down"
  exit 0
else
  # host is not "down"
  exit 1
fi
```

@AlexGustafsson does this seem right to you? This has generally been working for me but took forever to figure out.

**Comment by AlexGustafsson** [comment] 2019-06-25 17:31
@amaisano Yeah, that seems to work!

**Comment by AlexGustafsson** [comment] 2019-06-25 17:32
Closing. Feel free to open it again if you believe that the issue is not solved.

**Closed by AlexGustafsson** 2019-06-25 17:32 UTC

**Comment by AlexGustafsson** [comment] 2020-07-21 15:40
I'm able to reproduce the issue. Investigating.
