### ISSUE TITLE
Windows shutdown command errors - NT_STATUS_OBJECT_NAME_NOT_FOUND

### ISSUE THREAD

**Issue by Garywoo** [AlexGustafsson/homebridge-wol#57] opened 2019-02-01 21:58 UTC
### Backstory
I set up WOL for my Windows PC on my RPi. The wake command works great, but the shutdown command is producing errors.

### Issue
The error NT_STATUS_OBJECT_NAME_NOT_FOUND is logged when the following shutdown command is sent:
`sudo net rpc shutdown --ipaddress 192.168.1.63 --user <username>%<password>`
I also tried without sudo, which produced the same error.

### Environment
* os & os version: Raspian9
* node version: v10.15.0
* homebridge version: v0.4.46
* homebridge-wol version: v3.2.4

### Configuration
My configuration looks like this:
```
"accessories": [
        {
            "accessory": "NetworkDevice",
            "name": "My PC",
            "mac": "<mac-address>",
            "ip": "192.168.1.63",
            "shutdownCommand": "sudo net rpc shutdown --ipaddress 192.168.1.63 --user <username>%<password>"
        }
    ],
```

### Log
```
[2/1/2019, 9:43:47 PM] [My PC] NetworkDevice "My PC" (192.168.1.63) went from status "Online" to "Shutting Down"
[2/1/2019, 9:43:48 PM] [My PC] An error occured while trying to shut down "My PC" (192.168.1.63): Error: Command failed: sudo net rpc shutdown --ipaddress 192.168.1.63 --user <username>%<password>
Could not initialise pipe winreg. Error was NT_STATUS_OBJECT_NAME_NOT_FOUND
```

**Comment by AlexGustafsson** [comment] 2019-02-02 08:35
This usually means that the service isn’t running on the Windows machine. By default, the net rpc service is turned off - so unless you’ve manually configured it on the Windows machine, the command will fail.

I should point out that I’ve had some issues with doing this in Windows in the past, but some users have succeeded. You can search through the issues to see previous discussion.

Closing this as this is an issue with using net rpc on windows and not the package itself. If you have further questions, don’t hesitate to ask them here - I will still respond even though the issue is closed.

**Closed by AlexGustafsson** 2019-02-02 08:35 UTC
