### ISSUE TITLE
pingCommand doesn't seem to be working as documented

### ISSUE THREAD

**Issue by mignz** [AlexGustafsson/homebridge-wol#76] opened 2019-09-29 18:07 UTC
This is my configuration:

```
{
    "accessory": "NetworkDevice",
    "name": "My PC",
    "ip": "10.0.0.10",
    "pingInterval": 5,
    "pingCommand": "curl -m 2 -s http://10.0.0.10:5001",
    "timeout": 2,
    "wakeGraceTime": 10,
    "shutdownCommand": "curl -s http://10.0.0.10:5001/.../suspend",
    "log": true,
    "logPinger": true
}
```

I am running homebridge-wol v3.2.4 and the pingCommand doesn't seem to be working properly. It always considers the machine to be running even when it's not.

I've tried running the curl command from another machine and it returns a code higher than 0 when sleeping and the code 0 when up:

Up:

    $ curl -m 2 -s 10.0.0.10:5001
    Ok
    $ echo $?
    0

Down:

    $ curl -m 2 -s 10.0.0.10:5001
    $ echo $?
    7

On that 5001 port I am running a small web server that returns the output "Ok". This is [Karpach Remote Shutdown PC](https://github.com/karpach/remote-shutdown-pc).

Also, on the Log:

```
[2019-9-29 19:20:04] Homebridge is running on port 51826.
[2019-9-29 19:20:04] [My PC] Pinger saw device online; setting to Online.
[2019-9-29 19:20:04] [My PC] NetworkDevice "My PC" (10.0.0.10) went from status "Offline" to "Online"
[2019-9-29 19:20:33] [My PC] NetworkDevice shutdown cycle started for "My PC" (10.0.0.10)
[2019-9-29 19:20:33] [My PC] Stopping pinger
[2019-9-29 19:20:33] [My PC] Starting pinger again in 15000 milli seconds
[2019-9-29 19:20:33] [My PC] Attempting to shut down "My PC" (10.0.0.10) using "curl -m 2 -s http://10.0.0.10:5001/.../suspend"
[2019-9-29 19:20:33] [My PC] NetworkDevice "My PC" (10.0.0.10) went from status "Online" to "Shutting Down"
[2019-9-29 19:20:35] [My PC] An error occured while trying to shut down "My PC" (10.0.0.10): Error: Command failed: curl -m 2 -s http://10.0.0.10:5001/.../suspend

[2019-9-29 19:20:35] [My PC] Stopping pinger
[2019-9-29 19:20:35] [My PC] Starting pinger at an interval of 5000 milli seconds
[2019-9-29 19:20:35] [My PC] Pinger saw device online; setting to Online.
[2019-9-29 19:20:35] [My PC] NetworkDevice "My PC" (10.0.0.10) went from status "Shutting Down" to "Online"
```

The shutdown command fails as it should because the machine is already offline. However, there's no log on the ping command failing.

**Comment by dcaccount** [comment] 2019-09-30 19:58
I have a similar issue here.
I have set pingInterval=60, so after having shut down the system, within 60 seconds Homebridge should show that the machine is off but it takes much longer to detect that it has been switched off.

Any idea? Thanks, Dan

**Comment by tanmaster** [comment] 2019-10-30 21:09
I made a pull request which (to me) looks like it fixes the bug.
You can view it [here](https://github.com/AlexGustafsson/homebridge-wol/pull/77/files).
The error is that this.pinging is set to true once in the first call of ping, but if pingCommand is set, this value is never set back to false. Thats why the ping function always immediately returns.
Also the pingCallback was called with false when it should be called with true, and true when it should be called with false.

**Comment by AlexGustafsson** [comment] 2019-11-04 10:34
@dcaccount That's slightly intended behavior. It is supposed to ping every interval, but it won't react until the same result is achieved five times in a row. Due to pings not being reliable, this code is intended to zero out any false positives and false negatives. It does come at the cost of longer time needed for a change to happen, but it can be balanced by lowering the `pingInterval`.

**Comment by AlexGustafsson** [comment] 2019-11-04 10:34
@tanmaster The change looks good. I've commented it in the PR for further discussion. @mignz are you able to test @tanmaster's change to see if it solved your issue?

**Comment by AlexGustafsson** [comment] 2019-11-05 13:22
@tanmaster's PR has been merged. If anyone feels like this issue has not been solved, feel free to reopen it.

**Closed by AlexGustafsson** 2019-11-05 13:22 UTC

**Comment by mignz** [comment] 2019-12-20 01:02
Sorry for the delay. Yes, it's working. Had to manually change `pinger.js` file as it's not on NPM yet.
